### PR TITLE
Make sure the Entity type provides a niche

### PR DESCRIPTION
**Pull request by adamreichold**
This enables enum layout optimisations implying relations like
```rust
size_of::<Entity>() == size_of::<Option<Entity>>()
```

### CODE REVIEW

**Comment by mlange-42** [comment]
As I think we can only gain something here this looks like a good thing. Does that only affect outside usage, or is `Option<Entity>` also used internally?

**Comment by adamreichold** [comment]
> As I think we can only gain something here this looks like a good thing. Does that only affect outside usage, or is `Option<Entity>` also used internally?

`Entity` and thereby `Option<Entity>` are never really used for the implementation of the ECS. The `Entity` component is kept up-to-date solely for sake of users of the library.

**Comment by mlange-42** [comment]
I still think there is no reason to not use this optimization.

**Comment by adamreichold** [comment]
> I still think there is no reason to not use this optimization.

Certainly. I was just waiting for the green check mark in the review box...

**Review by mlange-42 — APPROVED** [review]

**Pull request merged**
